env:
  browser: true
  es2022: true

extends:
  - plugin:@typescript-eslint/recommended
  - plugin:@next/next/recommended
  - prettier

parser: '@typescript-eslint/parser'

parserOptions:
  project: tsconfig.json
  ecmaVersion: latest
  sourceType: module

rules:
  no-plusplus: [ "error", { "allowForLoopAfterthoughts": true } ]
